
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='tess-astrometry',
    version='0.1.0',
    description='Tools to measure astrometry of TESS Solar System objects',
    python_requires='==3.*,>=3.8.0',
    author='Jeff Smith',
    author_email='jsmith@seti.org',
    packages=[],
    package_dir={"": "src"},
    package_data={},
    install_requires=['lightkurve==2.*,>=2.0.10', 'tess-ephem==0.*,>=0.3.0'],
    extras_require={"dev": ["pytest==6.*,>=6.2.4"]},
)
